sudo: false
language: node_js
node_js: "9.4.0"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn
  - yarn build-prod
  - yarn test
notifications:
  on_failure: change # always|never
  on_success: never
